apiVersion: apps/v1
kind: Deployment
metadata:
  name: oink-bot
  labels:
    app: oink-bot
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oink-bot
  template:
    metadata:
      labels:
        app: oink-bot
        version: v1
    spec:
      containers:
      - name: oink-bot
        image: oink-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: oink-bot-secrets
              key: database-url
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: oink-bot-secrets
              key: discord-token
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oink-bot-secrets
              key: discord-client-id
        - name: DISCORD_GUILD_ID
          valueFrom:
            secretKeyRef:
              name: oink-bot-secrets
              key: discord-guild-id
        - name: REDIS_URL
          value: "redis://oink-bot-redis:6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: oink-bot-service
  labels:
    app: oink-bot
spec:
  selector:
    app: oink-bot
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: oink-bot-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: <base64-encoded-database-url>
  discord-token: <base64-encoded-discord-token>
  discord-client-id: <base64-encoded-discord-client-id>
  discord-guild-id: <base64-encoded-discord-guild-id>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oink-bot-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
