apiVersion: apps/v1
kind: Deployment
metadata:
  name: oink-bot-postgres
  labels:
    app: oink-bot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oink-bot-postgres
  template:
    metadata:
      labels:
        app: oink-bot-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "oink_bot"
        - name: POSTGRES_USER
          value: "oink_bot"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oink-bot-secrets
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - oink_bot
            - -d
            - oink_bot
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - oink_bot
            - -d
            - oink_bot
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 999
          capabilities:
            drop:
            - ALL
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-init
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: oink-bot-postgres
  labels:
    app: oink-bot-postgres
spec:
  selector:
    app: oink-bot-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    -- Initialize database schema
    CREATE DATABASE IF NOT EXISTS oink_bot;
    GRANT ALL PRIVILEGES ON DATABASE oink_bot TO oink_bot;
